### ISSUE TITLE
Info.plist missing?

### ISSUE THREAD

**Issue by RyuX51** [karhoo/karhoo-ios-ui-sdk#3]
I'm having a hard time tring to use KarhooUISDK with CocoaPods. It's telling me that it's missing the `Info.plist`:

<img width="275" alt="Screenshot 2020-07-07 at 00 51 07" src="https://user-images.githubusercontent.com/1900479/86662432-ff9eb680-bfec-11ea-96d1-789e6dffdf8c.png">

Would you be able to help me with that?

I need to use `use_frameworks!` in my `Podfile` if that's important. You don't have that in your example `Podfile`.

**Comment by JeevanThandi** [comment]
Hey @RyuX51 

Thanks for your interest in the UISDK. Could you try adding:

```
pod 'KarhooUISDK', :git => 'https://github.com/Karhoo/karhoo-ios-ui-sdk.git', :tag => '1.2.5'
```
 
to your podfile instead? We need to update our documentation as it is likely pointing to an out of date binary dependency rather than this new repo (source dependency). After making this change 'use_frameworks!' should work fine as this pod reference will be dynamic.

**Comment by RyuX51** [comment]
Upgrading to 1.2.5 solves it, thank you very much. 👍🏻
Since I'm here, can I ask you if there's an ETA for the Android part of the UI SDK?

**Comment by JeevanThandi** [comment]
Excellent! anytime :-) 

The android UI SDK is available (closed source) - https://developer.karhoo.com/docs/using-the-ui-sdk#android where you can access the latest AAR  

and the android network SDK is available (open source) - https://github.com/karhoo/karhoo-android-sdk 

We plan to open source the Android UISDK within Q3 2020 :-)

**Comment by RyuX51** [comment]
That's great news. Thank you for the update and keep up the good work.
